// INSIGHTS_URL=http://127.0.0.1:5173 PLAYWRIGHT_PATH=/path/to/playwright node tests/insights-browser.cjs
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright')
const assert = require('node:assert/strict')
const { pathToFileURL } = require('node:url')
const path = require('node:path')
;(async () => {
  const { insightArticles, insightsCopy } = await import(pathToFileURL(path.resolve(__dirname, '../src/data/insights.js')))
  const base = process.env.INSIGHTS_URL || 'http://127.0.0.1:5173'
  const browser = await chromium.launch()
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 1000 }, reducedMotion: 'reduce' })
    const errors = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('console', msg => { if (msg.type() === 'error' && !msg.text().includes('net::ERR_')) errors.push(msg.text()) })
    await page.addInitScript(() => localStorage.setItem('azul-cookies', JSON.stringify({ analytics: false })))
    for (const lang of ['en', 'es']) {
      await page.goto(`${base}/insights`)
      await page.locator('.languages button').nth(lang === 'en' ? 0 : 1).click()
      const copy = insightsCopy[lang]
      await page.waitForFunction(title => document.title === title, copy.meta.title)
      assert.equal(await page.locator('.insights-grid .insight-card').count(), 6)
      for (const width of [375, 768, 1280, 1920]) {
        await page.setViewportSize({ width, height: 1000 })
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `Hub overflow ${lang} ${width}`)
      }
      await page.getByRole('button', { name: copy.filters[2].label, exact: true }).click()
      await page.waitForFunction(() => document.querySelectorAll('.insights-grid .insight-card').length === 1)
      assert.equal(await page.locator('.insights-grid .insight-card').count(), 1)
      assert.ok(page.url().includes('topic=reviews'))
      await page.getByRole('searchbox', { name: copy.search }).fill('no-results-xyz')
      await page.waitForSelector('.insights-empty')
      assert.equal(await page.locator('.insights-empty').count(), 1)
      await page.getByRole('button', { name: copy.reset }).click()
      await page.waitForFunction(() => document.querySelectorAll('.insights-grid .insight-card').length === 6)
      assert.equal(await page.locator('.insights-grid .insight-card').count(), 6)
      await page.getByRole('searchbox', { name: copy.search }).fill(lang === 'en' ? 'calls' : 'resenas')
      await page.waitForFunction(() => document.querySelectorAll('.insights-grid .insight-card').length > 0 && document.querySelectorAll('.insights-grid .insight-card').length < 6)
      assert.ok(await page.locator('.insights-grid .insight-card').count() > 0)
      await page.locator('.insights-grid .insight-card a').first().click()
      await page.waitForSelector('.insight-body')
      await page.goBack()
      await page.waitForSelector('.insights-library')
      assert.equal(await page.getByRole('searchbox', { name: copy.search }).inputValue(), lang === 'en' ? 'calls' : 'resenas')
      for (const article of insightArticles) {
        await page.goto(`${base}/insights/${article.slug}`)
        await page.waitForFunction(title => document.title === title, `${copy.articles[article.slug].title} | Azul`)
        assert.equal(await page.locator('main h1').count(), 1)
        assert.equal(await page.locator('.pending').count(), 0)
        assert.equal(await page.locator('.desktop-nav a[href="/insights"]').getAttribute('aria-current'), 'page')
        assert.equal(await page.locator('meta[name="description"]').getAttribute('content'), copy.articles[article.slug].dek)
        for (const width of [375, 768, 1280, 1920]) {
          await page.setViewportSize({ width, height: 1000 })
          assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${article.slug} overflow ${lang} ${width}`)
        }
        await page.locator('.insight-sidebar a[href="#section-3"]').click()
        await page.waitForFunction(() => document.querySelector('.insight-sidebar a[href="#section-3"]').getAttribute('aria-current') === 'location')
        assert.ok(await page.locator('#section-3').evaluate(el => Math.abs(el.getBoundingClientRect().top) < 190))
        await page.locator('.insight-checklist input').first().check()
        assert.ok((await page.locator('.insight-checklist-count').innerText()).startsWith('1 /'))
        const other = lang === 'en' ? 'es' : 'en'
        await page.locator('.languages button').nth(other === 'en' ? 0 : 1).click()
        await page.waitForFunction(title => document.title === title, `${insightsCopy[other].articles[article.slug].title} | Azul`)
        assert.equal(await page.locator('.insight-checklist input').first().isChecked(), true)
        await page.locator('.languages button').nth(lang === 'en' ? 0 : 1).click()
        const progress = await page.locator('.reading-progress span').evaluate(el => getComputedStyle(el).transform)
        assert.notEqual(progress, 'matrix(0, 0, 0, 1, 0, 0)')
        assert.equal(await page.locator('.insight-related .insight-card').count(), 2)
      }
    }
    // Clipboard failure still provides a selectable URL.
    await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('blocked') } } }))
    await page.locator('.insight-sidebar button').click()
    assert.ok((await page.locator('.insight-share-fallback').inputValue()).endsWith(insightArticles.at(-1).slug))
    await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async value => { window.copiedArticle = value } } }))
    await page.locator('.insight-sidebar button').click()
    assert.ok(await page.evaluate(() => window.copiedArticle.includes('/insights/')))
    await page.keyboard.press('Tab')
    await page.locator('.insight-back').focus()
    assert.notEqual(await page.locator('.insight-back').evaluate(el => getComputedStyle(el).outlineStyle), 'none')
    await page.locator('.insight-related .insight-card a').first().click()
    await page.waitForSelector('.insight-body')
    await page.waitForFunction(() => document.querySelectorAll('.insight-checklist input:checked').length === 0)
    assert.equal(await page.locator('.insight-checklist input:checked').count(), 0)
    // Capture normal-motion reveals as well as reduced-motion layouts.
    await page.goto(`${base}/insights`)
    await page.locator('.languages button').first().click()
    await page.emulateMedia({ reducedMotion: 'no-preference' })
    await page.reload()
    await page.locator('.insights-library').scrollIntoViewIfNeeded()
    await page.waitForTimeout(1800)
    await page.locator('.insight-card a').first().hover()
    await page.locator('.insight-card a').first().click()
    await page.waitForSelector('.insight-body')
    await page.waitForTimeout(1300)
    assert.equal(await page.locator('main h1').isVisible(), true)
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.setViewportSize({ width: 1280, height: 1000 })
    await page.goto(`${base}/insights`)
    await page.screenshot({ path: '/private/tmp/azul-insights-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 375, height: 900 })
    await page.screenshot({ path: '/private/tmp/azul-insights-mobile.png', fullPage: true })
    await page.goto(`${base}/insights/${insightArticles[0].slug}`)
    await page.screenshot({ path: '/private/tmp/azul-article-mobile.png', fullPage: true })
    await page.setViewportSize({ width: 1280, height: 1000 })
    await page.screenshot({ path: '/private/tmp/azul-article-desktop.png', fullPage: true })
    assert.deepEqual(errors, [])
    console.log('PASS: hub + six articles in EN/ES at 375/768/1280/1920px; filters, search/history, TOC, checklists, metadata, sharing, related links, motion, focus, and no runtime errors.')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
